#!/usr/bin/env bash

MAX_PAGES=20
RESULTS_PAGES_DIR=pages
UNIQ_LISTINGS_FILE=listing-ids
LISTING_PAGES_DIR=listings

getResultsPages() {
  keyword=$1

  mkdir -p $RESULTS_PAGES_DIR

  # active Next   = <a href="/auto/search/index?page=2" title="Go forward 1 page">Next »</a>
  # inactive Next = <span style="color: gray"> | Next</span>

  for pageNum in $(seq 1 $MAX_PAGES); do
    url="http://www.ksl.com/auto/search/index?keyword=$keyword&page=$pageNum"
    echo "downloading $url"
    curl $url > $RESULTS_PAGES_DIR/page$pageNum
    sleep 1
  done
}

extractListingIds() {
  # example /auto/listing/2162162?ad_cid=1
  grep -oE '/auto\/listing\/[0-9]+' $RESULTS_PAGES_DIR/page* |cut -d '/' -f5 |uniq > $UNIQ_LISTINGS_FILE
}

getListings() {
  mkdir -p $LISTING_PAGES_DIR

  for id in $(cat $UNIQ_LISTINGS_FILE); do
    path=$LISTING_PAGES_DIR/$id

    if test -f $path; then
      echo $path exists
    else
      url="http://www.ksl.com/auto/listing/$id"
      echo "downloading $id $url"
      curl "$url" > $path
    fi

    sleep 0.05
  done
}

main() {
  searchTerm=$1
  # getResultsPages $searchTerm
  extractListingIds
  getListings
}

main $@
